# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ncSHDikc5qhvl8FmPcbCpJTKpZ6lWk7h
"""

n = 5

for i in range(1, 11):

    result = n * i
    print(f"{n} x {i} = {result}")